// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'firebase_options.dart';
/// // ...
  ///await Firebase.initializeApp(
    ///options: DefaultFirebaseOptions.currentPlatform,
 /// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PKf85JS677PchuAB9KdBn_KpbBMjoaM',
    appId: '1:478956223182:web:0f6131c4b6a05adab32e9f',
    messagingSenderId: '478956223182',
    projectId: 'holterapp-96dd8',
    authDomain: 'holterapp-96dd8.firebaseapp.com',
    storageBucket: 'holterapp-96dd8.appspot.com',
    measurementId: 'G-J6QBKZQ5V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZm333EYx49HElkk6DKBaMpvkJiERbJb4',
    appId: '1:478956223182:android:a407e4abd00c09a3b32e9f',
    messagingSenderId: '478956223182',
    projectId: 'holterapp-96dd8',
    storageBucket: 'holterapp-96dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU53WC9r5u8KTA1o2YOAfcxvLsizLJZZ4',
    appId: '1:478956223182:ios:86d6317850efd8ceb32e9f',
    messagingSenderId: '478956223182',
    projectId: 'holterapp-96dd8',
    storageBucket: 'holterapp-96dd8.appspot.com',
    iosBundleId: 'com.example.holterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU53WC9r5u8KTA1o2YOAfcxvLsizLJZZ4',
    appId: '1:478956223182:ios:fbab7adc93186429b32e9f',
    messagingSenderId: '478956223182',
    projectId: 'holterapp-96dd8',
    storageBucket: 'holterapp-96dd8.appspot.com',
    iosBundleId: 'com.example.holterApp.RunnerTests',
  );
}
